apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: homeroom

vars:
- name: APPLICATION_NAME
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: homeroom-environ
  fieldref:
    fieldPath: data.APPLICATION_NAME

resources:
- resources/service-account.yaml
- resources/role-binding.yaml
- resources/configs-config-map.yaml
- resources/environ-config-map.yaml
- resources/deployment.yaml
- resources/service.yaml
- resources/ingress.yaml
