apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: homeroom

resources:
- resources/service-account.yaml
- resources/role-binding.yaml
- resources/configs-config-map.yaml
- resources/environ-config-map.yaml
- resources/deployment.yaml
- resources/service.yaml
- resources/ingress.yaml
